POST http://localhost:8080/auth/login HTTP/1.1
Content-Type: application/json

{
  "username":"usera",
  "password":"passs"
}


###
POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json

{
  "username":"",
  "password":""
}
###
GET http://localhost:8080/users HTTP/1.1


###
PUT http://localhost:8080/users/20 HTTP/1.1
Content-Type: application/json

{
  "username":"user",
  "password":"passs"
}

###
DELETE  http://localhost:8080/users/1 HTTP/1.1

###
POST http://localhost:8080/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE1NzA2Mjg5NTgsInVzZXJfaWQiOjN9.ZDOOPI5KmxGc38ps2HQU2p0jEn4Xhl1Q0wPn6nvn8V8

{
  "title":"titleew",
  "content":"passsfaf",
}
###
GET http://localhost:8080/posts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE1NzA2Mjg5NTgsInVzZXJfaWQiOjN9.ZDOOPI5KmxGc38ps2HQU2p0jEn4Xhl1Q0wPn6nvn8V8

###
PUT http://localhost:8080/posts/2 HTTP/1.1
Content-Type: application/json

{
  "title":"titleesfafafafaw",
  "content":"passsfaf",
  "author_id":1
}

###
DELETE  http://localhost:8080/posts/1 HTTP/1.1
Authorization: 